### ISSUE TITLE
Null reference thrown when trying to instantiate MVC Controller

### ISSUE THREAD

**Issue by jatwigg** [LeeCheneler/EasyIoC#9]
Apologies if I'm missing something but I've followed the MVC guide in the readme but I get a NullReferenceException on line 45 of EasyMvcControllerFactory.
After inspecting the requestContext.RouteData.DataTokens there is no Namespaces kvp present.

I've managed to get it working by replacing the namespace check with 
```
 pair.Key.EndsWith(controllerName, StringComparison,StringComparison.CurrentCultureIgnoreCase)
```
and removing the namespace lookup all together but I'm not sure if this is a good solution.

Is there a way to get the Namespace in the DataTokens? I can't seem to find any reference to namespaces in the DataTokens property online.

**Comment by LeeCheneler** [comment]
Hmm, I'm not too sure. Truth be told I moved to Asp.Net Core and node very quickly after writing this and Asp.Net Core has a good DI framework in place already so I haven't been maintaining this library at all sorry 😔

You can raise a PR of you have a decent fix for this that won't break it for other users 🙂

**Comment by jatwigg** [comment]
Hi Lee,
I've decided to go with Unity.Mvc for DI now.
I'm not too sure of the impacts of my change so I won't submit a PR.
Thanks anyway :)
